# permissions for end users to edit restarts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autoreload-cm-deployment
    app.kubernetes.io/managed-by: kustomize
  name: restart-editor-role
rules:
- apiGroups:
  - auto.test.com
  resources:
  - restarts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auto.test.com
  resources:
  - restarts/status
  verbs:
  - get
